[package]
name = "hmac-sha1"
version = "0.1.0"
authors = ["Philip Woolford <woolford.philip@gmail.com>"]
license-file = "LICENSE"

[lib]
name = "hmacsha1"
path = "src/lib.rs"

[dependencies]
sha1 = "0.2.0"

[dev-dependencies]
rustc-serialize = "0.3"